name: Run Appium Tests

on:
  push:
    branches:
      - IOS-execution

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      LAMBDATEST_USERNAME: ${{ secrets.LAMBDATEST_USERNAME }}
      LAMBDATEST_ACCESS_KEY: ${{ secrets.LAMBDATEST_ACCESSKEY }}
      APPIUM_SERVER_URL: https://suraj.warade:c5gyNDEr11w2acPLuruyQ9Su3DUz5yYeqvWs6Pq8qAK6EaZtMF@mobile-hub.lambdatest.com/wd/hub

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install appium-python-client
        pip install robotframework-appiumlibrary
        pip install PyPDF2
        sudo apt-get install jq

    - name: Run Appium tests
      run: |
        # Run your Appium tests
        robot -i demo --variable appium_server:"$APPIUM_SERVER_URL" --variable deviceName:"iPhone 14 Pro" --variable platformVersion:"16.0" --variable app:lt:"//APP1016061291724664628238139" Mobile/IOS/KC/TestCases
