
name: Run Web Tests on LambdaTest

on:
  push:
    branches:
      - web-execution

jobs:
  test:
    runs-on: ubuntu-latest

    env:
          LAMBDATEST_USERNAME: ${{ secrets.USERNAME }}
          LAMBDATEST_ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Robot Framework and Dependencies
      run: |
        pip install -r requirements.txt
        pip install robotframework-seleniumlibrary
        sudo apt-get install jq

    - name: Run Tests on All Devices from JSON
      run: |
        jq -c '.[]' web_environment_combinations.json | while IFS= read -r device; do
          # Extract variables from the JSON object
          BROWSER=$(echo "$device" | jq -r '.browser')
          ENV=$(echo "$device" | jq -r '.env_url')
          # Construct and run the Robot Framework command
          echo "Running tests on '$BROWSER' with environment '$ENV'"
          pabot --testlevelsplit --variable browser:"$BROWSER" --variable env:"$ENV" --variable LT_USERNAME:"$LAMBDATEST_USERNAME" --variable LT_ACCESS_KEY:"$LAMBDATEST_ACCESS_KEY"  Web/RR/TestCases/Players/Players_test.robot
        done
