name: Run Web Tests on LambdaTest

on: 
  push:
    branches:
      - web-execution

jobs:
  test:
    runs-on: ubuntu-latest

    env:
          LAMBDATEST_USERNAME: ${{ secrets.LAMBDATEST_USERNAME }}
          LAMBDATEST_ACCESS_KEY: ${{ secrets.LAMBDATEST_ACCESSKEY }}
          SERVER_URL: https://suraj.warade:c5gyNDEr11w2acPLuruyQ9Su3DUz5yYeqvWs6Pq8qAK6EaZtMF@hub.lambdatest.com/wd/hub
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Robot Framework and Dependencies
      run: |
        pip install -r requirements.txt
        pip install robotframework-seleniumlibrary
        sudo apt-get install jq

    - name: Run Tests on All Devices from JSON
      run: |
          # Read the JSON file and generate commands
          jq -c '.[]' web_environment_combinations.json | while IFS= read -r device; do
            BROWSER=$(echo "$browser" | jq -r '.browser')
            ENV=$(echo "$env" | jq -r '.env')
            # Construct and run the Robot Framework command
            echo "Running tests on '$BROWSER' with env '$ENV'"
            pabot --testlevelsplit --variable browser:"$BROWSER" --variable env:"$ENV" --variable appium_server:"$SERVER_URL" Web/RR/TestCases/Players/Players_test.robot
          done